version: '3'

services:
  hostel-mess-app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./data:/usr/src/app/data
    environment:
      - NODE_ENV=production
    restart: unless-stopped

volumes:
  data: